services:
  - type: web
    name: find-nutrition-ocr
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: "/"
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract