services:
  - type: web
    name: find-nutrition-ocr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
    dockerfilePath: ./Dockerfile